python main2.py ^
  --mode=train_and_eval ^
  --train_file_pattern=./projects/Signals/train/*.tfrecord  ^
  --val_file_pattern=./projects/Signals/valid/*.tfrecord ^
  --model_name=efficientdet-d0 ^
  --hparams="input_rand_hflip=False,num_classes=5,label_map=./projects/Signals/label_map.yaml" ^
  --model_dir=./projects/Signals/models ^
  --label_map_pbtxt=./projects/Signals/label_map.pbtxt ^
  --eval_dir=./projects/Signals/eval ^
  --ckpt=efficientdet-d0  ^
  --train_batch_size=4 ^
  --early_stopping=map ^
  --patience=10 ^
  --eval_batch_size=1 ^
  --eval_samples=200  ^
  --num_examples_per_epoch=400 ^
  --num_epochs=100
